In [ ]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import sklearn
import seaborn as sns
import re

In [ ]:
df=pd.read_csv("sample.csv")

In [ ]:
df.head()

,transaction_id,user_id,transaction_amount,transaction_timestamp,user_location,merchant_location,merchant_category,device_id,device_type,payment_method,account_balance,transaction_status,ip_address,amt
0,TXN-3E3A44E74819,USR0020,7457.251963207814,2024-03-14T11:40:15.672605,JAI,ahmedabad,Travel,DEV-C894B8F5,mobile,Card,140227.79,success,192.96.196.31,NaN
1,TXN-84B8FC890498,USR0043,308.51678134343047,1717321977,Delhi,DEL,Travel,DEV-EC8BBC24,mobile,UPI,122548.77,success,192.138.55.249,NaN
2,TXN-95B71538FFAD,USR0044,₹3159,1710796175,jaipur,Jaipur,NaN,D??,web,Card,168910.49,success,192.73.41.151,NaN
3,TXN-657F2702B5B2,USR0060,5349.73,07/02/2024 03:50:23,BENGALURU,BENGALURU,Education,DEV-888653EA,web,UPI,9046.00,success,192.231.148.119,NaN
4,TXN-84C8BBF69256,USR0020,2454.5652128035144,"March 13, 2024 11:25 PM",jaipur,Jaipur,Utilities,DEV-C894B8F5,mobile,Card,153095.35,success,192.96.196.139,NaN

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1447 entries, 0 to 1446
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   transaction_id         1447 non-null   str
 1   user_id                1447 non-null   str
 2   transaction_amount     1374 non-null   str
 3   transaction_timestamp  1447 non-null   str
 4   user_location          1447 non-null   str
 5   merchant_location      1447 non-null   str
 6   merchant_category      1369 non-null   str
 7   device_id              1374 non-null   str
 8   device_type            1447 non-null   str
 9   payment_method         1373 non-null   str
 10  account_balance        1373 non-null   float64
 11  transaction_status     1447 non-null   str
 12  ip_address             1368 non-null   str
 13  amt                    49 non-null     str
dtypes: float64(1), str(13)
memory usage: 321.7 KB

In [ ]:
df.isnull().sum()

transaction_id              0
user_id                     0
transaction_amount         73
transaction_timestamp       0
user_location               0
merchant_location           0
merchant_category          78
device_id                  73
device_type                 0
payment_method             74
account_balance            74
transaction_status          0
ip_address                 79
amt                      1398
dtype: int64

In [ ]:
df.columns

Index(['transaction_id', 'user_id', 'transaction_amount',
       'transaction_timestamp', 'user_location', 'merchant_location',
       'merchant_category', 'device_id', 'device_type', 'payment_method',
       'account_balance', 'transaction_status', 'ip_address', 'amt'],
      dtype='str')

In [ ]:
df.describe()

       account_balance
count      1373.000000
mean      73386.952403
std       55553.341123
min           0.000000
25%       23885.610000
50%       68661.030000
75%      121395.610000
max      191245.660000

In [ ]:
df.duplicated().sum()

np.int64(21)

In [ ]:
df.shape

(1447, 14)

In [ ]:
# Importing one hot encoder
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(drop="first")

In [ ]:
# Checking the values in device_Type
df["device_type"].value_counts()

# Converting device_type str to numerical data using one hot
device_type_encoded=encoder.fit_transform(df[["device_type"]]).toarray()
encoded_df=pd.DataFrame(device_type_encoded,columns=encoder.get_feature_names_out(["device_type"]))
df=pd.concat([df,encoded_df],axis=1)

# Dropping the device_type
df.drop("device_type",axis=1,inplace=True)

In [ ]:
df.head()

,transaction_id,user_id,transaction_amount,transaction_timestamp,user_location,merchant_location,merchant_category,device_id,payment_method,account_balance,transaction_status,ip_address,amt,device_type_mobile,device_type_web
0,TXN-3E3A44E74819,USR0020,7457.251963207814,2024-03-14T11:40:15.672605,JAI,ahmedabad,Travel,DEV-C894B8F5,Card,140227.79,success,192.96.196.31,NaN,1.0,0.0
1,TXN-84B8FC890498,USR0043,308.51678134343047,1717321977,Delhi,DEL,Travel,DEV-EC8BBC24,UPI,122548.77,success,192.138.55.249,NaN,1.0,0.0
2,TXN-95B71538FFAD,USR0044,₹3159,1710796175,jaipur,Jaipur,NaN,D??,Card,168910.49,success,192.73.41.151,NaN,0.0,1.0
3,TXN-657F2702B5B2,USR0060,5349.73,07/02/2024 03:50:23,BENGALURU,BENGALURU,Education,DEV-888653EA,UPI,9046.00,success,192.231.148.119,NaN,0.0,1.0
4,TXN-84C8BBF69256,USR0020,2454.5652128035144,"March 13, 2024 11:25 PM",jaipur,Jaipur,Utilities,DEV-C894B8F5,Card,153095.35,success,192.96.196.139,NaN,1.0,0.0

In [ ]:
df.columns

Index(['transaction_id', 'user_id', 'transaction_amount',
       'transaction_timestamp', 'user_location', 'merchant_location',
       'merchant_category', 'device_id', 'payment_method', 'account_balance',
       'transaction_status', 'ip_address', 'amt', 'device_type_mobile',
       'device_type_web'],
      dtype='str')

In [ ]:
df.columns

Index(['transaction_id', 'user_id', 'transaction_amount',
       'transaction_timestamp', 'user_location', 'merchant_location',
       'merchant_category', 'device_id', 'payment_method', 'account_balance',
       'transaction_status', 'ip_address', 'amt', 'device_type_mobile',
       'device_type_web'],
      dtype='str')

In [ ]:
# Finding values in Payment Method
df['payment_method'].value_counts()

# Converting payment_method to numerical value by get dummies
df=pd.get_dummies(df,columns=['payment_method'],prefix='pay',drop_first=True,dtype=int)

In [ ]:
df.columns

Index(['transaction_id', 'user_id', 'transaction_amount',
       'transaction_timestamp', 'user_location', 'merchant_location',
       'merchant_category', 'device_id', 'account_balance',
       'transaction_status', 'ip_address', 'amt', 'device_type_mobile',
       'device_type_web', 'pay_NetBanking', 'pay_UPI', 'pay_Wallet'],
      dtype='str')

In [ ]:
df["transaction_amount"].value_counts()

transaction_amount
1678106.56            10
0.0                    9
1.0                    8
₹5067                  2
7.78                   2
                      ..
12953.17               1
2672.7143498167743     1
615 INR                1
956.784541866445       1
2332.363563500775      1
Name: count, Length: 1348, dtype: int64

In [ ]:
# 1. Create a "Flag" column (1 if missing, 0 if present)
# This explicitly captures the fraud signal mentioned in the brief
df['is_amount_missing'] = df['transaction_amount'].isnull().astype(int)

# 2. Impute (fill) the missing values so the model doesn't crash
# Filling with 0 is standard practice here since a missing amount functionally
# acts like a zero-dollar ping to the system.
df['transaction_amount'] = df['transaction_amount'].fillna(0)

# Check our work!
print("Remaining nulls in transaction_amount:", df['transaction_amount'].isnull().sum())


def clean_amount_text(val):
    if pd.isna(val):
        return 0.0

    # Convert to string and strip out everything except digits and decimals
    cleaned_str = re.sub(r'[^\d.]', '', str(val))


# Apply the regex cleaner
df['transaction_amount'] = df['transaction_amount'].apply(clean_amount_text)


# Drop the redundant 'amt' shadow column
df = df.drop(columns=['amt'])

Remaining nulls in transaction_amount: 0

In [ ]:
df["transaction_amount"]

0       7457.251963
1        308.516781
2       3159.000000
3       5349.730000
4       2454.565213
           ...
1442    2672.714350
1443     615.000000
1444     956.784542
1445    2332.363564
1446       0.000000
Name: transaction_amount, Length: 1447, dtype: float64

In [ ]:
df[df['transaction_amount'].isnull()]

Empty DataFrame
Columns: [transaction_id, user_id, transaction_amount, transaction_timestamp, user_location, merchant_location, merchant_category, device_id, account_balance, transaction_status, ip_address, device_type_mobile, device_type_web, pay_NetBanking, pay_UPI, pay_Wallet, is_amount_missing]
Index: []

In [ ]:
df["is_amount_missing"].value_counts()

is_amount_missing
0    1374
1      73
Name: count, dtype: int64

In [ ]:
# Finding the values count in transaction_status
df["transaction_status"].value_counts()


# Using the dummies function to convert the transaction_status columns to numerical values
df=pd.get_dummies(df,columns=['transaction_status'],prefix="transaction_status",dtype=int)

In [ ]:
# Merchant category

df["merchant_category"].value_counts()

merchant_category
Electronics      181
Utilities        146
Travel           144
Clothing         135
Grocery          129
Fuel             126
Entertainment    125
Healthcare       120
Education        119
Food & Dining    111
T#                 2
Cl??               2
Fue#               2
Food & Di#         1
Food & Di...       1
Enterta#           1
C#                 1
Ut...              1
Tra                1
Ent                1
Groce#             1
Food & Di??        1
Utili              1
Ent#               1
Food ??            1
Healthca??         1
Clothin??          1
T??                1
Enter??            1
Edu??              1
Enterta...         1
Groce...           1
Clo...             1
Tr??               1
Food & D           1
Clothin...         1
H#                 1
Utili??            1
Fu??               1
Gr...              1
Name: count, dtype: int64

In [ ]:
def clean_merchant_category(val):
    # 1. Handle the 78 missing values we found earlier
    if pd.isna(val):
        return 'Unknown'

    val_str = str(val).strip()

    # 2. Define our clean, valid categories (from your top 10 value counts)
    valid_categories = [
        'Electronics', 'Utilities', 'Travel', 'Clothing', 'Grocery',
        'Fuel', 'Entertainment', 'Healthcare', 'Education', 'Food & Dining'
    ]

    # If it's already a perfect match, just return it
    if val_str in valid_categories:
        return val_str

    # 3. Handle the corrupted tail using substring matching
    val_lower = val_str.lower()

    # We check the first 2 or 3 letters of the corrupted string
    if val_lower.startswith('el'): return 'Electronics'
    if val_lower.startswith('ut'): return 'Utilities'
    if val_lower.startswith('tr') or val_lower.startswith('t#') or val_lower.startswith('t?'): return 'Travel'
    if val_lower.startswith('cl') or val_lower.startswith('c#'): return 'Clothing'
    if val_lower.startswith('gr'): return 'Grocery'
    if val_lower.startswith('fu'): return 'Fuel'
    if val_lower.startswith('en'): return 'Entertainment'
    if val_lower.startswith('he') or val_lower.startswith('h#'): return 'Healthcare'
    if val_lower.startswith('ed'): return 'Education'
    if val_lower.startswith('fo'): return 'Food & Dining'

    # Fallback just in case something completely weird slips through
    return 'Unknown'

# Apply the cleaner to the column
df['merchant_category'] = df['merchant_category'].apply(clean_merchant_category)

# Check your work! It should now be perfectly clean.
print(df['merchant_category'].value_counts())

# Step 2: Apply One-Hot Encoding
# We use drop_first=False to ensure we keep 'merchant_Unknown' as a specific feature
df = pd.get_dummies(df, columns=['merchant_category'], prefix='merchant', drop_first=False, dtype=int)

# Check the new columns to ensure it worked!
print([col for col in df.columns if 'merchant_' in col])

merchant_category
Electronics      181
Travel           149
Utilities        149
Clothing         141
Grocery          132
Entertainment    130
Fuel             129
Healthcare       122
Education        120
Food & Dining    116
Unknown           78
Name: count, dtype: int64
['merchant_location', 'merchant_Clothing', 'merchant_Education', 'merchant_Electronics', 'merchant_Entertainment', 'merchant_Food & Dining', 'merchant_Fuel', 'merchant_Grocery', 'merchant_Healthcare', 'merchant_Travel', 'merchant_Unknown', 'merchant_Utilities']

In [ ]:
df["account_balance"].value_counts()

account_balance
0.00         197
177866.52      4
73726.38       3
45793.96       3
1768.90        3
            ...
174015.45      1
118582.16      1
119773.72      1
73970.71       1
107131.51      1
Name: count, Length: 1048, dtype: int64

In [ ]:
df["account_balance"].isnull().sum()

np.int64(74)

In [ ]:
# 1. Flag the missing balances (The Fraud Signal)
df['is_balance_missing'] = df['account_balance'].isnull().astype(int)

# 2. Force the column to be numeric (just in case there are hidden text strings)
# We fill missing values with -1 so the model knows it's fundamentally different from a true 0.00 balance
df['account_balance'] = pd.to_numeric(df['account_balance'], errors='coerce').fillna(-1.0)

# 3. Engineer the "Balance Utilization" Feature
# We use np.where to safely divide, avoiding "Division by Zero" errors when the balance is 0.00 or -1.0
df['balance_utilization'] = np.where(
    df['account_balance'] > 0,
    df['transaction_amount'] / df['account_balance'],
    -1.0  # Assign -1 if the balance is 0 or missing
)

# Check the new engineered feature!
print(df[['transaction_amount', 'account_balance', 'balance_utilization']].head())

   transaction_amount  account_balance  balance_utilization
0         7457.251963        140227.79             0.053180
1          308.516781        122548.77             0.002518
2         3159.000000        168910.49             0.018702
3         5349.730000          9046.00             0.591392
4         2454.565213        153095.35             0.016033

In [ ]:
df["account_balance"].value_counts()

account_balance
 0.00         197
-1.00          74
 177866.52      4
 73726.38       3
 45793.96       3
             ...
 174015.45      1
 118582.16      1
 119773.72      1
 73970.71       1
 107131.51      1
Name: count, Length: 1049, dtype: int64

In [ ]:
df.head()

,transaction_id,user_id,transaction_amount,transaction_timestamp,user_location,merchant_location,device_id,account_balance,ip_address,device_type_mobile,...,merchant_Entertainment,merchant_Food & Dining,merchant_Fuel,merchant_Grocery,merchant_Healthcare,merchant_Travel,merchant_Unknown,merchant_Utilities,is_balance_missing,balance_utilization
0,TXN-3E3A44E74819,USR0020,7457.251963,2024-03-14T11:40:15.672605,JAI,ahmedabad,DEV-C894B8F5,140227.79,192.96.196.31,1.0,...,0,0,0,0,0,1,0,0,0,0.053180
1,TXN-84B8FC890498,USR0043,308.516781,1717321977,Delhi,DEL,DEV-EC8BBC24,122548.77,192.138.55.249,1.0,...,0,0,0,0,0,1,0,0,0,0.002518
2,TXN-95B71538FFAD,USR0044,3159.000000,1710796175,jaipur,Jaipur,D??,168910.49,192.73.41.151,0.0,...,0,0,0,0,0,0,1,0,0,0.018702
3,TXN-657F2702B5B2,USR0060,5349.730000,07/02/2024 03:50:23,BENGALURU,BENGALURU,DEV-888653EA,9046.00,192.231.148.119,0.0,...,0,0,0,0,0,0,0,0,0,0.591392
4,TXN-84C8BBF69256,USR0020,2454.565213,"March 13, 2024 11:25 PM",jaipur,Jaipur,DEV-C894B8F5,153095.35,192.96.196.139,1.0,...,0,0,0,0,0,0,0,1,0,0.016033

In [ ]:
df.columns

Index(['transaction_id', 'user_id', 'transaction_amount',
       'transaction_timestamp', 'user_location', 'merchant_location',
       'device_id', 'account_balance', 'ip_address', 'device_type_mobile',
       'device_type_web', 'pay_NetBanking', 'pay_UPI', 'pay_Wallet',
       'is_amount_missing', 'transaction_status_failed',
       'transaction_status_pending', 'transaction_status_success',
       'merchant_Clothing', 'merchant_Education', 'merchant_Electronics',
       'merchant_Entertainment', 'merchant_Food & Dining', 'merchant_Fuel',
       'merchant_Grocery', 'merchant_Healthcare', 'merchant_Travel',
       'merchant_Unknown', 'merchant_Utilities', 'is_balance_missing',
       'balance_utilization'],
      dtype='str')

In [ ]:
df["device_id"]

0       DEV-C894B8F5
1       DEV-EC8BBC24
2                D??
3       DEV-888653EA
4       DEV-C894B8F5
            ...
1442    DEV-8657F3E2
1443    ATO-7D32C693
1444    DEV-54C67087
1445    DEV-D7256DA2
1446    DEV-8F2A3284
Name: device_id, Length: 1447, dtype: str

In [ ]:
# Count how many unique users are associated with each device
users_per_device = df.groupby('device_id')['user_id'].nunique().to_dict()

# Map this count back to our main dataframe
df['unique_users_on_device'] = df['device_id'].map(users_per_device)

# If a device is missing (NaN), we just assume 1 user to be safe
df['unique_users_on_device'] = df['unique_users_on_device'].fillna(1)

In [ ]:
df["ip_address"].value_counts()

ip_address
not_an_ip          8
192.168..1         7
999.168.1.1        5
192.228.28.250     3
192.96.196.45      3
                  ..
192.38.168.146     1
140.18.71.75       1
192.62.225.88      1
192.109.213.177    1
192.83.126.174     1
Name: count, Length: 1290, dtype: int64

In [ ]:
import ipaddress
import numpy as np

def check_ip_suspicious(ip):
    # If it is completely missing (NaN), it is suspicious
    if pd.isna(ip) or ip in ["", "NA", "$N/A$", "nan", "NULL"]:
        return 1 # Flag as suspicious (1)

    ip_str = str(ip).strip()

    # Ask Python's official networking library if the IP is mathematically valid
    try:
        ipaddress.ip_address(ip_str)
        return 0 # It is valid, not suspicious (0)
    except ValueError:
        return 1 # It failed validation! Flag as suspicious (1)

# 1. Engineer the "Suspicious IP" Fraud Feature
df['is_ip_suspicious'] = df['ip_address'].apply(check_ip_suspicious)

# 2. Check how many bad/missing IPs we caught!
print("Total suspicious IPs found:", df['is_ip_suspicious'].sum())

# 3. Drop the raw text column (Machine Learning models can't read raw IP strings anyway)
df = df.drop(columns=['ip_address'])

Total suspicious IPs found: 107

In [ ]:
# Pattern Founds